### ISSUE TITLE
We need a separate branch that only highlights % and the word following it as an error. 

### ISSUE THREAD

**Issue by aaronjwalker** [aaronjwalker/RepositextMarkdownEditing#5]
We need another copy of RepositextMarkdownEditing that will have all of the current error highlighting turned off except for a small set of the current error highlighting and 1 new additional error. The errors you implemented in commit  2910acfb6af17d3040e7d0ede91997a5aa0bc7b3 should be left turned on. The errors you implemented in that commit error when the attribute name that follows a paragraph is not spelled correctly. 

The new additional error highlighting is needed at every location that where there is a `%`. The `%` and the following word needs to be highlighted as an error.

We do not want these changes implemented in the master copy of this and and subsequent additions or changes to the code in the repositext branch shouldn't need to be transferred to this. 

I would assume that the best way to handle this is to create this in a separate branch. Please call it repositext-audio.

**Comment by maliayas** [comment]
If you want to have both at the same time, we can define it as another syntax file in master.

**Comment by aaronjwalker** [comment]
Yes. That sounds better. Sorry I didn't think of that.

**Comment by aaronjwalker** [comment]
Can you change it to so that the error highlighting will stop at ellipsis or em dashes? In the example below it would be preferable not to highlight the ellipsis and the word following it.

![screen shot 2014-09-11 at 9 21 38 am](https://cloud.githubusercontent.com/assets/4036470/4234412/b027c46a-39b6-11e4-834d-a3c6d33a217b.png)

**Comment by maliayas** [comment]
- New syntax file is created.
- `repositext-audio` branch is deleted.
- Em dash and ellipsis stops the error highlighting.

**Comment by aaronjwalker** [comment]
Looks good
