### ISSUE TITLE
Error highlighting around % for Repositext Audio

### ISSUE THREAD

**Issue by aaronjwalker** [aaronjwalker/RepositextMarkdownEditing#6]
Some of the errors we add here will probably end needing to be added to Repositext Kramdwon also but which ones will only be evident after adding them here and seeing if they are applicable to the other.

I would like to add some error highlighting with orange or yellow (doesn't matter which). A short list is below This list will grow over time.
Any of the error highlighting below should supersede red highlighting.
Error on:
- `[word]%…[word]` (These should always be [word]…%[word])
- `“%` (This is erring in Repositext Kramdown. We turned it off for Respositext Audio so that only instances of %[word] were highlighted red.)
- `‘%`
- `%[whitespace]`

**Comment by maliayas** [comment]
Warnings are like below. If you want to change the colors, we can play on it.

![ekran goruntusu 2014 12 13 00_59_09](https://cloud.githubusercontent.com/assets/844008/5420850/48142198-8263-11e4-9f83-65f7ccaf18ea.png)

**Comment by aaronjwalker** [comment]
This looks good. 

Can we add these to the list as well?
- `%?`
- `%.`
- `%!`
- Error if `%` is placed into a header
- Any number of `%` in a row above one.

Can we have it error if the `%` is in the middle of a word?

**Comment by maliayas** [comment]
> `%`

Do you want to highlight every single `%`?

**Comment by aaronjwalker** [comment]
They are already highlighted aren't they? If they are in what is considered a correct location they are included in the red highlight with a word. If they are in an unacceptable location they are highlighted orange.

**Comment by maliayas** [comment]
OK.

> Any number of % in a row above one.

By "in a row" do you mean contiguous?

> Error if % is placed into a header

such as: ??

```
# This is a % header
```

**Comment by aaronjwalker** [comment]
Okay, sorry, I misunderstood your previous comment. No I don't want to highlight single `%` as an error. 
Yes I meant contiguous.
Your example of a header error is correct.

**Comment by maliayas** [comment]
Could you check my latest commit pelase?

Single `%`s are highlighted as orange at the moment.

**Comment by aaronjwalker** [comment]
Ok I see my mistake in the list above the single % was supposed to be followed by a period.

`%.`

The error highlighting appears to be working except the single percents need to revert back to how they were implemented before. 

Sorry about that.

**Comment by aaronjwalker** [comment]
In the example below the `%` is not being highlighted. A `%` should be highlighted orange no matter where it exists in a header.

`# *Convinced %Then Concerned*`

**Comment by maliayas** [comment]
I've done them. Now we highlight all % in headers but when % is inside another inline item (e.g. bold or italic) this rule doesn't work 100%. Because I can define bold/italic's "%" rule but can't tell ST that "if the bold/italic is in a header behave in another way". So, valid % won't be highlighted in a headers's inline item (bold, italic etc.). If it was already invalid, then no problem, it'll be highlighted.

Waiting for your feedback.

**Comment by aaronjwalker** [comment]
All `%` are being highlighted orange now through out the file.

**Comment by maliayas** [comment]
Hmm. "%" rules have grown a little wildly. They are overriding each other. I propose redefining "%" rules from scratch. Could you make list of current % requirements please?

**Comment by aaronjwalker** [comment]
They are all being highlighted correctly now. So maybe we can address the new list if needed in the future.
