### ISSUE TITLE
Highlight `.omit` green

### ISSUE THREAD

**Issue by aaronjwalker** [aaronjwalker/RepositextMarkdownEditing#8]
We would like to highlight all paragraphs with ials that contain `.omit` in green.
List of these:
`{: .normal .omit}`
`{: .nomral_pn .omit}`
`{: .omit .stanza}`
`{: .omit .song}`
`{: .omit .scr}`
`{: .omit .q}`
`{: .omit .reading}`

We would like for this highlighting to highlight the previous paragraph as green also. The classes above exist lines by themselves directly following the paragraph they pertain to. They are seperated by a `\n` only.

Example:

`[“Let us stand together, to our feet.`
`{: .normal .omit}`

We would want the entire example above highlighted in green. If that is not possible the ial itself will do.

**Comment by maliayas** [comment]
We can not highlight all the paragraph. That would collide with the markdown paragraph definition. ST allows you to define the begin line and the end line of your target area, you can tell it what to include in that area but not what not to include. It will parse ahead until it sees your end line definition. For this reason it will give unwanted green highlightings (like multiple unrelated paragraphs highlited fully green):

I'll work on highlighting the ial.

**Comment by maliayas** [comment]
Here it is:

![ekran goruntusu 2014 12 13 00_11_29](https://cloud.githubusercontent.com/assets/844008/5420475/963d6d5c-825e-11e4-8233-cf5157969c1b.png)

I've implemented this in all the three language definitions. In case you don't want that, we can undo some.

**Comment by aaronjwalker** [comment]
I like how you implemented it and we can try it out in all three for now.
