### ISSUE TITLE
Why is this highlighted?

### ISSUE THREAD

**Issue by aaronjwalker** [aaronjwalker/RepositextMarkdownEditing#9]
![screen shot 2014-10-01 at 4 08 15 pm](https://cloud.githubusercontent.com/assets/4036470/4482272/f76d02d6-49a6-11e4-8904-8a080bff4332.png)

**Comment by maliayas** [comment]
Normally space wasn't allowed there. Now I've changed it to allow one space. But if you wish, we can allow any amount of space there.

**Comment by aaronjwalker** [comment]
Allowing only one space is good.
